// Code generated by tutone: DO NOT EDIT
package entities

import (
	"context"

	"github.com/newrelic/newrelic-client-go/pkg/common"
	"github.com/newrelic/newrelic-client-go/pkg/errors"
)

// Adds the provided tags to your specified entity, without deleting existing ones.
//  The maximum number of tag-values per entity is 100; if the sum of existing and new tag-values if over the limit this mutation will fail.
//
//  For details and mutation examples, visit [our docs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial).
func (a *Entities) TaggingAddTagsToEntity(
	gUID common.EntityGUID,
	tags []TaggingTagInput,
) (*TaggingMutationResult, error) {
	return a.TaggingAddTagsToEntityWithContext(context.Background(),
		gUID,
		tags,
	)
}

// Adds the provided tags to your specified entity, without deleting existing ones.
//  The maximum number of tag-values per entity is 100; if the sum of existing and new tag-values if over the limit this mutation will fail.
//
//  For details and mutation examples, visit [our docs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial).
func (a *Entities) TaggingAddTagsToEntityWithContext(
	ctx context.Context,
	gUID common.EntityGUID,
	tags []TaggingTagInput,
) (*TaggingMutationResult, error) {

	resp := TaggingAddTagsToEntityQueryResponse{}
	vars := map[string]interface{}{
		"guid": gUID,
		"tags": tags,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, TaggingAddTagsToEntityMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.TaggingMutationResult, nil
}

type TaggingAddTagsToEntityQueryResponse struct {
	TaggingMutationResult TaggingMutationResult `json:"TaggingAddTagsToEntity"`
}

const TaggingAddTagsToEntityMutation = `mutation(
	$guid: EntityGuid!,
	$tags: [TaggingTagInput!]!,
) { taggingAddTagsToEntity(
	guid: $guid,
	tags: $tags,
) {
	errors {
		message
		type
	}
} }`

// Delete specific tag keys from the entity.
//
//  For details and mutation examples, visit [our docs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial).
func (a *Entities) TaggingDeleteTagFromEntity(
	gUID common.EntityGUID,
	tagKeys []string,
) (*TaggingMutationResult, error) {
	return a.TaggingDeleteTagFromEntityWithContext(context.Background(),
		gUID,
		tagKeys,
	)
}

// Delete specific tag keys from the entity.
//
//  For details and mutation examples, visit [our docs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial).
func (a *Entities) TaggingDeleteTagFromEntityWithContext(
	ctx context.Context,
	gUID common.EntityGUID,
	tagKeys []string,
) (*TaggingMutationResult, error) {

	resp := TaggingDeleteTagFromEntityQueryResponse{}
	vars := map[string]interface{}{
		"guid":    gUID,
		"tagKeys": tagKeys,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, TaggingDeleteTagFromEntityMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.TaggingMutationResult, nil
}

type TaggingDeleteTagFromEntityQueryResponse struct {
	TaggingMutationResult TaggingMutationResult `json:"TaggingDeleteTagFromEntity"`
}

const TaggingDeleteTagFromEntityMutation = `mutation(
	$guid: EntityGuid!,
	$tagKeys: [String!]!,
) { taggingDeleteTagFromEntity(
	guid: $guid,
	tagKeys: $tagKeys,
) {
	errors {
		message
		type
	}
} }`

// Delete specific tag key-values from the entity.
//
//  For details and mutation examples, visit [our docs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial).
func (a *Entities) TaggingDeleteTagValuesFromEntity(
	gUID common.EntityGUID,
	tagValues []TaggingTagValueInput,
) (*TaggingMutationResult, error) {
	return a.TaggingDeleteTagValuesFromEntityWithContext(context.Background(),
		gUID,
		tagValues,
	)
}

// Delete specific tag key-values from the entity.
//
//  For details and mutation examples, visit [our docs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial).
func (a *Entities) TaggingDeleteTagValuesFromEntityWithContext(
	ctx context.Context,
	gUID common.EntityGUID,
	tagValues []TaggingTagValueInput,
) (*TaggingMutationResult, error) {

	resp := TaggingDeleteTagValuesFromEntityQueryResponse{}
	vars := map[string]interface{}{
		"guid":      gUID,
		"tagValues": tagValues,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, TaggingDeleteTagValuesFromEntityMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.TaggingMutationResult, nil
}

type TaggingDeleteTagValuesFromEntityQueryResponse struct {
	TaggingMutationResult TaggingMutationResult `json:"TaggingDeleteTagValuesFromEntity"`
}

const TaggingDeleteTagValuesFromEntityMutation = `mutation(
	$guid: EntityGuid!,
	$tagValues: [TaggingTagValueInput!]!,
) { taggingDeleteTagValuesFromEntity(
	guid: $guid,
	tagValues: $tagValues,
) {
	errors {
		message
		type
	}
} }`

// Replaces the entity's entire set of tags with the provided tag set.
//  The maximum number of tag-values per entity is 100; if more than 100 tag-values are provided this mutation will fail.
//
//  For details and mutation examples, visit [our docs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial).
func (a *Entities) TaggingReplaceTagsOnEntity(
	gUID common.EntityGUID,
	tags []TaggingTagInput,
) (*TaggingMutationResult, error) {
	return a.TaggingReplaceTagsOnEntityWithContext(context.Background(),
		gUID,
		tags,
	)
}

// Replaces the entity's entire set of tags with the provided tag set.
//  The maximum number of tag-values per entity is 100; if more than 100 tag-values are provided this mutation will fail.
//
//  For details and mutation examples, visit [our docs](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-tagging-api-tutorial).
func (a *Entities) TaggingReplaceTagsOnEntityWithContext(
	ctx context.Context,
	gUID common.EntityGUID,
	tags []TaggingTagInput,
) (*TaggingMutationResult, error) {

	resp := TaggingReplaceTagsOnEntityQueryResponse{}
	vars := map[string]interface{}{
		"guid": gUID,
		"tags": tags,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, TaggingReplaceTagsOnEntityMutation, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.TaggingMutationResult, nil
}

type TaggingReplaceTagsOnEntityQueryResponse struct {
	TaggingMutationResult TaggingMutationResult `json:"TaggingReplaceTagsOnEntity"`
}

const TaggingReplaceTagsOnEntityMutation = `mutation(
	$guid: EntityGuid!,
	$tags: [TaggingTagInput!]!,
) { taggingReplaceTagsOnEntity(
	guid: $guid,
	tags: $tags,
) {
	errors {
		message
		type
	}
} }`

// Fetch a list of entities.
//
// You can fetch a max of 25 entities in one query.
//
// For more details on entities, visit our [entity docs](https://docs.newrelic.com/docs/apis/graphql-api/tutorials/use-new-relic-graphql-api-query-entities).
func (a *Entities) GetEntities(
	gUIDs []common.EntityGUID,
) (*[]EntityInterface, error) {
	return a.GetEntitiesWithContext(context.Background(),
		gUIDs,
	)
}

// Fetch a list of entities.
//
// You can fetch a max of 25 entities in one query.
//
// For more details on entities, visit our [entity docs](https://docs.newrelic.com/docs/apis/graphql-api/tutorials/use-new-relic-graphql-api-query-entities).
func (a *Entities) GetEntitiesWithContext(
	ctx context.Context,
	gUIDs []common.EntityGUID,
) (*[]EntityInterface, error) {

	resp := entitiesResponse{}
	vars := map[string]interface{}{
		"guids": gUIDs,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, getEntitiesQuery, vars, &resp); err != nil {
		return nil, err
	}

	if len(resp.Actor.Entities) == 0 {
		return nil, errors.NewNotFound("")
	}

	return &resp.Actor.Entities, nil
}

const getEntitiesQuery = `query(
	$guids: [EntityGuid]!,
) { actor { entities(
	guids: $guids,
) {
	account {
		id
		name
		region {
			code
			id
			name
		}
		reportingEventTypes
	}
	accountId
	alertSeverity
	alertStatus
	dashboardTemplates {
		mosaicTemplate
	}
	domain
	entityType
	goldenMetrics {
		context {
			account
			guid
		}
		metrics {
			name
			query
			title
			unit
		}
	}
	goldenSignalValues {
		fullyQualifiedSignalName
		name
		summaryValue
		units
		values
	}
	goldenSignalValuesV2 {
		signalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		timeIndex
	}
	goldenTags {
		context {
			account
			guid
		}
		tags {
			key
		}
	}
	guid
	indexedAt
	name
	permalink
	recentAlertViolations {
		agentUrl
		alertSeverity
		alertStatus
		closedAt
		label
		level
		openedAt
		violationId
		violationUrl
	}
	recommendedServiceLevel {
		indicators {
			category
			description
			name
		}
	}
	relatedDashboards {
		dashboardGuids
		dashboards {
			__typename
			accountId
			alertSeverity
			alertStatus
			domain
			entityType
			guid
			indexedAt
			name
			permalink
			reporting
			type
			... on ApmAgentInstrumentedServiceEntityOutline {
				__typename
				applicationId
				language
			}
			... on ApmApplicationEntityOutline {
				__typename
				applicationId
				language
				... on ApmAgentInstrumentedServiceEntityOutline {
					__typename
				}
			}
			... on ApmDatabaseInstanceEntityOutline {
				__typename
				host
				portOrPath
				vendor
			}
			... on ApmExternalServiceEntityOutline {
				__typename
				host
			}
			... on BrowserApplicationEntityOutline {
				__typename
				agentInstallType
				applicationId
				servingApmApplicationId
			}
			... on DashboardEntityOutline {
				__typename
				createdAt
				dashboardParentGuid
				permissions
				updatedAt
			}
			... on ExternalEntityOutline {
				__typename
			}
			... on GenericEntityOutline {
				__typename
			}
			... on GenericInfrastructureEntityOutline {
				__typename
				integrationTypeCode
			}
			... on GenericServiceEntityOutline {
				__typename
			}
			... on InfrastructureAwsLambdaFunctionEntityOutline {
				__typename
				integrationTypeCode
				runtime
			}
			... on InfrastructureHostEntityOutline {
				__typename
			}
			... on MobileApplicationEntityOutline {
				__typename
				applicationId
			}
			... on SecureCredentialEntityOutline {
				__typename
				description
				secureCredentialId
				updatedAt
			}
			... on ServiceEntityOutline {
				__typename
				... on ApmAgentInstrumentedServiceEntityOutline {
					__typename
					applicationId
					language
				}
				... on GenericServiceEntityOutline {
					__typename
				}
			}
			... on SyntheticMonitorEntityOutline {
				__typename
				monitorId
				monitorType
				monitoredUrl
				period
			}
			... on ThirdPartyServiceEntityOutline {
				__typename
				... on GenericServiceEntityOutline {
					__typename
				}
			}
			... on UnavailableEntityOutline {
				__typename
			}
			... on WorkloadEntityOutline {
				__typename
				createdAt
				updatedAt
			}
		}
	}
	relatedEntities {
		count
		nextCursor
		results {
			__typename
			createdAt
			type
			... on EntityRelationshipDetectedEdge {
				__typename
			}
			... on EntityRelationshipUserDefinedEdge {
				__typename
			}
		}
	}
	relationships {
		source {
			accountId
			entityType
			guid
		}
		target {
			accountId
			entityType
			guid
		}
		type
	}
	reporting
	serviceLevel {
		indicators {
			createdAt
			description
			entityGuid
			id
			name
			updatedAt
		}
	}
	summaryMetrics {
		name
		title
		value {
			__typename
			unit
			... on EntitySummaryNumericMetricValue {
				__typename
				numericValue
			}
			... on EntitySummaryStringMetricValue {
				__typename
				stringValue
			}
		}
	}
	tags {
		key
		values
	}
	tagsWithMetadata {
		key
		values {
			mutable
			value
		}
	}
	tracingSummary {
		errorTraceCount
		percentOfAllErrorTraces
	}
	type
	uiTemplates {
		template
	}
	... on ApmAgentInstrumentedServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		apmBrowserSummary {
			ajaxRequestThroughput
			ajaxResponseTimeAverage
			jsErrorRate
			pageLoadThroughput
			pageLoadTimeAverage
		}
		apmSettings {
			tracerType
		}
		apmSummary {
			apdexScore
			errorRate
			hostCount
			instanceCount
			nonWebResponseTimeAverage
			nonWebThroughput
			responseTimeAverage
			throughput
			webResponseTimeAverage
			webThroughput
		}
		applicationId
		dashboardTemplates {
			mosaicTemplate
		}
		deployments {
			changelog
			description
			permalink
			revision
			timestamp
			user
		}
		errorGroupCount {
			count
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		language
		metricNormalizationRules {
			action
			applicationGuid
			applicationName
			createdAt
			enabled
			evalOrder
			id
			matchExpression
			notes
			replacement
			terminateChain
		}
		recentAgentActivity {
			activityType
			description
			permalink
			timestamp
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		runningAgentVersions {
			maxVersion
			minVersion
		}
		settings {
			apdexTarget
			serverSideConfig
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on ApmApplicationEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		apmBrowserSummary {
			ajaxRequestThroughput
			ajaxResponseTimeAverage
			jsErrorRate
			pageLoadThroughput
			pageLoadTimeAverage
		}
		apmSettings {
			tracerType
		}
		apmSummary {
			apdexScore
			errorRate
			hostCount
			instanceCount
			nonWebResponseTimeAverage
			nonWebThroughput
			responseTimeAverage
			throughput
			webResponseTimeAverage
			webThroughput
		}
		applicationId
		dashboardTemplates {
			mosaicTemplate
		}
		deployments {
			changelog
			description
			permalink
			revision
			timestamp
			user
		}
		errorGroupCount {
			count
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		language
		metricNormalizationRules {
			action
			applicationGuid
			applicationName
			createdAt
			enabled
			evalOrder
			id
			matchExpression
			notes
			replacement
			terminateChain
		}
		recentAgentActivity {
			activityType
			description
			permalink
			timestamp
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		runningAgentVersions {
			maxVersion
			minVersion
		}
		settings {
			apdexTarget
			serverSideConfig
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		... on ApmAgentInstrumentedServiceEntity {
			__typename
		}
	}
	... on ApmDatabaseInstanceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		host
		portOrPath
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		vendor
	}
	... on ApmExternalServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		externalSummary {
			responseTimeAverage
			throughput
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		host
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on BrowserApplicationEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		agentInstallType
		applicationId
		browserSummary {
			ajaxRequestThroughput
			ajaxResponseTimeAverage
			jsErrorRate
			pageLoadThroughput
			pageLoadTimeAverage
			pageLoadTimeMedian
			spaResponseTimeAverage
			spaResponseTimeMedian
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		metricNormalizationRules {
			action
			applicationGuid
			applicationName
			createdAt
			enabled
			evalOrder
			id
			matchExpression
			notes
			replacement
			terminateChain
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		runningAgentVersions {
			maxVersion
			minVersion
		}
		servingApmApplicationId
		settings {
			apdexTarget
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on DashboardEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		createdAt
		createdAtInternal
		dashboardParentGuid
		dashboardTemplates {
			mosaicTemplate
		}
		description
		descriptionInternal
		editableInternal
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		owner {
			email
			userId
		}
		ownerEmailInternal
		pages {
			createdAt
			description
			guid
			name
			updatedAt
		}
		pagesInternal {
			createdAt
			description
			editable
			gridColumnCount
			guid
			name
			ownerEmail
			updatedAt
			visibility
		}
		permissions
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		updatedAt
		updatedAtInternal
		visibilityInternal
	}
	... on ExternalEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on GenericEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on GenericInfrastructureEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		integrationTypeCode
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on GenericServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on InfrastructureAwsLambdaFunctionEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		integrationTypeCode
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		runtime
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on InfrastructureHostEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		availableServices {
			displayName
			guid
			processId
			status
			strategy
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		hostSummary {
			cpuUtilizationPercent
			diskUsedPercent
			memoryUsedPercent
			networkReceiveRate
			networkTransmitRate
			servicesCount
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on MobileApplicationEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		applicationId
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		metricNormalizationRules {
			action
			applicationGuid
			applicationName
			createdAt
			enabled
			evalOrder
			id
			matchExpression
			notes
			replacement
			terminateChain
		}
		mobileSummary {
			appLaunchCount
			crashCount
			crashRate
			httpErrorRate
			httpRequestCount
			httpRequestRate
			httpResponseTimeAverage
			mobileSessionCount
			networkFailureRate
			usersAffectedCount
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on SecureCredentialEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		description
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		secureCredentialId
		secureCredentialSummary {
			failingMonitorCount
			monitorCount
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		updatedAt
	}
	... on ServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		... on ApmAgentInstrumentedServiceEntity {
			__typename
			applicationId
			language
		}
		... on GenericServiceEntity {
			__typename
		}
	}
	... on SyntheticMonitorEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		monitorId
		monitorSummary {
			loadSizeAverage
			loadTimeP50
			loadTimeP95
			locationsFailing
			locationsRunning
			status
			successRate
		}
		monitorType
		monitoredUrl
		period
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on ThirdPartyServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		... on GenericServiceEntity {
			__typename
		}
	}
	... on UnavailableEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on WorkloadEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		createdAt
		createdByUser {
			email
			gravatar
			id
			name
		}
		dashboardTemplates {
			mosaicTemplate
		}
		errorGroupCount {
			count
		}
		errorGroupNotificationPolicy {
			id
			name
			workloadGuid
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		updatedAt
		workloadStatus {
			description
			statusSource
			statusValue
			summary
		}
	}
} } }`

// Fetch a single entity.
//
// For more details on entities, visit our [entity docs](https://docs.newrelic.com/docs/apis/graphql-api/tutorials/use-new-relic-graphql-api-query-entities).
func (a *Entities) GetEntity(
	gUID common.EntityGUID,
) (*EntityInterface, error) {
	return a.GetEntityWithContext(context.Background(),
		gUID,
	)
}

// Fetch a single entity.
//
// For more details on entities, visit our [entity docs](https://docs.newrelic.com/docs/apis/graphql-api/tutorials/use-new-relic-graphql-api-query-entities).
func (a *Entities) GetEntityWithContext(
	ctx context.Context,
	gUID common.EntityGUID,
) (*EntityInterface, error) {

	resp := entityResponse{}
	vars := map[string]interface{}{
		"guid": gUID,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, getEntityQuery, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.Actor.Entity, nil
}

const getEntityQuery = `query(
	$guid: EntityGuid!,
) { actor { entity(
	guid: $guid,
) {
	account {
		id
		name
		region {
			code
			id
			name
		}
		reportingEventTypes
	}
	accountId
	alertSeverity
	alertStatus
	dashboardTemplates {
		mosaicTemplate
	}
	domain
	entityType
	goldenMetrics {
		context {
			account
			guid
		}
		metrics {
			name
			query
			title
			unit
		}
	}
	goldenSignalValues {
		fullyQualifiedSignalName
		name
		summaryValue
		units
		values
	}
	goldenSignalValuesV2 {
		signalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		timeIndex
	}
	goldenTags {
		context {
			account
			guid
		}
		tags {
			key
		}
	}
	guid
	indexedAt
	name
	permalink
	recentAlertViolations {
		agentUrl
		alertSeverity
		alertStatus
		closedAt
		label
		level
		openedAt
		violationId
		violationUrl
	}
	recommendedServiceLevel {
		indicators {
			category
			description
			name
		}
	}
	relatedDashboards {
		dashboardGuids
		dashboards {
			__typename
			accountId
			alertSeverity
			alertStatus
			domain
			entityType
			guid
			indexedAt
			name
			permalink
			reporting
			type
			... on ApmAgentInstrumentedServiceEntityOutline {
				__typename
				applicationId
				language
			}
			... on ApmApplicationEntityOutline {
				__typename
				applicationId
				language
				... on ApmAgentInstrumentedServiceEntityOutline {
					__typename
				}
			}
			... on ApmDatabaseInstanceEntityOutline {
				__typename
				host
				portOrPath
				vendor
			}
			... on ApmExternalServiceEntityOutline {
				__typename
				host
			}
			... on BrowserApplicationEntityOutline {
				__typename
				agentInstallType
				applicationId
				servingApmApplicationId
			}
			... on DashboardEntityOutline {
				__typename
				createdAt
				dashboardParentGuid
				permissions
				updatedAt
			}
			... on ExternalEntityOutline {
				__typename
			}
			... on GenericEntityOutline {
				__typename
			}
			... on GenericInfrastructureEntityOutline {
				__typename
				integrationTypeCode
			}
			... on GenericServiceEntityOutline {
				__typename
			}
			... on InfrastructureAwsLambdaFunctionEntityOutline {
				__typename
				integrationTypeCode
				runtime
			}
			... on InfrastructureHostEntityOutline {
				__typename
			}
			... on MobileApplicationEntityOutline {
				__typename
				applicationId
			}
			... on SecureCredentialEntityOutline {
				__typename
				description
				secureCredentialId
				updatedAt
			}
			... on ServiceEntityOutline {
				__typename
				... on ApmAgentInstrumentedServiceEntityOutline {
					__typename
					applicationId
					language
				}
				... on GenericServiceEntityOutline {
					__typename
				}
			}
			... on SyntheticMonitorEntityOutline {
				__typename
				monitorId
				monitorType
				monitoredUrl
				period
			}
			... on ThirdPartyServiceEntityOutline {
				__typename
				... on GenericServiceEntityOutline {
					__typename
				}
			}
			... on UnavailableEntityOutline {
				__typename
			}
			... on WorkloadEntityOutline {
				__typename
				createdAt
				updatedAt
			}
		}
	}
	relatedEntities {
		count
		nextCursor
		results {
			__typename
			createdAt
			type
			... on EntityRelationshipDetectedEdge {
				__typename
			}
			... on EntityRelationshipUserDefinedEdge {
				__typename
			}
		}
	}
	relationships {
		source {
			accountId
			entityType
			guid
		}
		target {
			accountId
			entityType
			guid
		}
		type
	}
	reporting
	serviceLevel {
		indicators {
			createdAt
			description
			entityGuid
			id
			name
			updatedAt
		}
	}
	summaryMetrics {
		name
		title
		value {
			__typename
			unit
			... on EntitySummaryNumericMetricValue {
				__typename
				numericValue
			}
			... on EntitySummaryStringMetricValue {
				__typename
				stringValue
			}
		}
	}
	tags {
		key
		values
	}
	tagsWithMetadata {
		key
		values {
			mutable
			value
		}
	}
	tracingSummary {
		errorTraceCount
		percentOfAllErrorTraces
	}
	type
	uiTemplates {
		template
	}
	... on ApmAgentInstrumentedServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		apmBrowserSummary {
			ajaxRequestThroughput
			ajaxResponseTimeAverage
			jsErrorRate
			pageLoadThroughput
			pageLoadTimeAverage
		}
		apmSettings {
			tracerType
		}
		apmSummary {
			apdexScore
			errorRate
			hostCount
			instanceCount
			nonWebResponseTimeAverage
			nonWebThroughput
			responseTimeAverage
			throughput
			webResponseTimeAverage
			webThroughput
		}
		applicationId
		dashboardTemplates {
			mosaicTemplate
		}
		deployments {
			changelog
			description
			permalink
			revision
			timestamp
			user
		}
		errorGroupCount {
			count
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		language
		metricNormalizationRules {
			action
			applicationGuid
			applicationName
			createdAt
			enabled
			evalOrder
			id
			matchExpression
			notes
			replacement
			terminateChain
		}
		recentAgentActivity {
			activityType
			description
			permalink
			timestamp
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		runningAgentVersions {
			maxVersion
			minVersion
		}
		settings {
			apdexTarget
			serverSideConfig
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on ApmApplicationEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		apmBrowserSummary {
			ajaxRequestThroughput
			ajaxResponseTimeAverage
			jsErrorRate
			pageLoadThroughput
			pageLoadTimeAverage
		}
		apmSettings {
			tracerType
		}
		apmSummary {
			apdexScore
			errorRate
			hostCount
			instanceCount
			nonWebResponseTimeAverage
			nonWebThroughput
			responseTimeAverage
			throughput
			webResponseTimeAverage
			webThroughput
		}
		applicationId
		dashboardTemplates {
			mosaicTemplate
		}
		deployments {
			changelog
			description
			permalink
			revision
			timestamp
			user
		}
		errorGroupCount {
			count
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		language
		metricNormalizationRules {
			action
			applicationGuid
			applicationName
			createdAt
			enabled
			evalOrder
			id
			matchExpression
			notes
			replacement
			terminateChain
		}
		recentAgentActivity {
			activityType
			description
			permalink
			timestamp
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		runningAgentVersions {
			maxVersion
			minVersion
		}
		settings {
			apdexTarget
			serverSideConfig
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		... on ApmAgentInstrumentedServiceEntity {
			__typename
		}
	}
	... on ApmDatabaseInstanceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		host
		portOrPath
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		vendor
	}
	... on ApmExternalServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		externalSummary {
			responseTimeAverage
			throughput
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		host
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on BrowserApplicationEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		agentInstallType
		applicationId
		browserSummary {
			ajaxRequestThroughput
			ajaxResponseTimeAverage
			jsErrorRate
			pageLoadThroughput
			pageLoadTimeAverage
			pageLoadTimeMedian
			spaResponseTimeAverage
			spaResponseTimeMedian
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		metricNormalizationRules {
			action
			applicationGuid
			applicationName
			createdAt
			enabled
			evalOrder
			id
			matchExpression
			notes
			replacement
			terminateChain
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		runningAgentVersions {
			maxVersion
			minVersion
		}
		servingApmApplicationId
		settings {
			apdexTarget
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on DashboardEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		createdAt
		createdAtInternal
		dashboardParentGuid
		dashboardTemplates {
			mosaicTemplate
		}
		description
		descriptionInternal
		editableInternal
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		owner {
			email
			userId
		}
		ownerEmailInternal
		pages {
			createdAt
			description
			guid
			name
			updatedAt
		}
		pagesInternal {
			createdAt
			description
			editable
			gridColumnCount
			guid
			name
			ownerEmail
			updatedAt
			visibility
		}
		permissions
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		updatedAt
		updatedAtInternal
		visibilityInternal
	}
	... on ExternalEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on GenericEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on GenericInfrastructureEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		integrationTypeCode
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on GenericServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on InfrastructureAwsLambdaFunctionEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		integrationTypeCode
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		runtime
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on InfrastructureHostEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		availableServices {
			displayName
			guid
			processId
			status
			strategy
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		hostSummary {
			cpuUtilizationPercent
			diskUsedPercent
			memoryUsedPercent
			networkReceiveRate
			networkTransmitRate
			servicesCount
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on MobileApplicationEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		applicationId
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		metricNormalizationRules {
			action
			applicationGuid
			applicationName
			createdAt
			enabled
			evalOrder
			id
			matchExpression
			notes
			replacement
			terminateChain
		}
		mobileSummary {
			appLaunchCount
			crashCount
			crashRate
			httpErrorRate
			httpRequestCount
			httpRequestRate
			httpResponseTimeAverage
			mobileSessionCount
			networkFailureRate
			usersAffectedCount
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on SecureCredentialEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		description
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		secureCredentialId
		secureCredentialSummary {
			failingMonitorCount
			monitorCount
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		updatedAt
	}
	... on ServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		... on ApmAgentInstrumentedServiceEntity {
			__typename
			applicationId
			language
		}
		... on GenericServiceEntity {
			__typename
		}
	}
	... on SyntheticMonitorEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		monitorId
		monitorSummary {
			loadSizeAverage
			loadTimeP50
			loadTimeP95
			locationsFailing
			locationsRunning
			status
			successRate
		}
		monitorType
		monitoredUrl
		period
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on ThirdPartyServiceEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		... on GenericServiceEntity {
			__typename
		}
	}
	... on UnavailableEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		dashboardTemplates {
			mosaicTemplate
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
	}
	... on WorkloadEntity {
		__typename
		account {
			id
			name
			reportingEventTypes
		}
		createdAt
		createdByUser {
			email
			gravatar
			id
			name
		}
		dashboardTemplates {
			mosaicTemplate
		}
		errorGroupCount {
			count
		}
		errorGroupNotificationPolicy {
			id
			name
			workloadGuid
		}
		goldenSignalValues {
			fullyQualifiedSignalName
			name
			summaryValue
			units
			values
		}
		goldenSignalValuesV2 {
			timeIndex
		}
		recentAlertViolations {
			agentUrl
			alertSeverity
			alertStatus
			closedAt
			label
			level
			openedAt
			violationId
			violationUrl
		}
		relatedDashboards {
			dashboardGuids
		}
		relatedEntities {
			count
			nextCursor
		}
		relationships {
			type
		}
		summaryMetrics {
			name
			title
		}
		tags {
			key
			values
		}
		tagsWithMetadata {
			key
		}
		tracingSummary {
			errorTraceCount
			percentOfAllErrorTraces
		}
		uiTemplates {
			template
		}
		updatedAt
		workloadStatus {
			description
			statusSource
			statusValue
			summary
		}
	}
} } }`

// Search for entities using a custom query.
//
// For more details on how to create a custom query
// and what entity data you can request, visit our
// [entity docs](https://docs.newrelic.com/docs/apis/graphql-api/tutorials/use-new-relic-graphql-api-query-entities).
//
// Note: you must supply either a `query` OR a `queryBuilder` argument, not both.
func (a *Entities) GetEntitySearch(
	options EntitySearchOptions,
	query string,
	queryBuilder EntitySearchQueryBuilder,
	sortBy []EntitySearchSortCriteria,
) (*EntitySearch, error) {
	return a.GetEntitySearchWithContext(context.Background(),
		options,
		query,
		queryBuilder,
		sortBy,
	)
}

// Search for entities using a custom query.
//
// For more details on how to create a custom query
// and what entity data you can request, visit our
// [entity docs](https://docs.newrelic.com/docs/apis/graphql-api/tutorials/use-new-relic-graphql-api-query-entities).
//
// Note: you must supply either a `query` OR a `queryBuilder` argument, not both.
func (a *Entities) GetEntitySearchWithContext(
	ctx context.Context,
	options EntitySearchOptions,
	query string,
	queryBuilder EntitySearchQueryBuilder,
	sortBy []EntitySearchSortCriteria,
) (*EntitySearch, error) {

	resp := entitySearchResponse{}
	vars := map[string]interface{}{
		"options":      options,
		"query":        query,
		"queryBuilder": queryBuilder,
		"sortBy":       sortBy,
	}

	if err := a.client.NerdGraphQueryWithContext(ctx, getEntitySearchQuery, vars, &resp); err != nil {
		return nil, err
	}

	return &resp.Actor.EntitySearch, nil
}

const getEntitySearchQuery = `query(
	$queryBuilder: EntitySearchQueryBuilder,
) { actor { entitySearch(
	queryBuilder: $queryBuilder,
) {
	count
	query
	results {
		accounts {
			id
			inRegion
			name
			reportingEventTypes
		}
		entities {
			__typename
			accountId
			alertSeverity
			alertStatus
			domain
			entityType
			guid
			indexedAt
			name
			permalink
			reporting
			type
			... on ApmAgentInstrumentedServiceEntityOutline {
				__typename
				applicationId
				language
			}
			... on ApmApplicationEntityOutline {
				__typename
				applicationId
				language
				... on ApmAgentInstrumentedServiceEntityOutline {
					__typename
				}
			}
			... on ApmDatabaseInstanceEntityOutline {
				__typename
				host
				portOrPath
				vendor
			}
			... on ApmExternalServiceEntityOutline {
				__typename
				host
			}
			... on BrowserApplicationEntityOutline {
				__typename
				agentInstallType
				applicationId
				servingApmApplicationId
			}
			... on DashboardEntityOutline {
				__typename
				createdAt
				dashboardParentGuid
				permissions
				updatedAt
			}
			... on ExternalEntityOutline {
				__typename
			}
			... on GenericEntityOutline {
				__typename
			}
			... on GenericInfrastructureEntityOutline {
				__typename
				integrationTypeCode
			}
			... on GenericServiceEntityOutline {
				__typename
			}
			... on InfrastructureAwsLambdaFunctionEntityOutline {
				__typename
				integrationTypeCode
				runtime
			}
			... on InfrastructureHostEntityOutline {
				__typename
			}
			... on MobileApplicationEntityOutline {
				__typename
				applicationId
			}
			... on SecureCredentialEntityOutline {
				__typename
				description
				secureCredentialId
				updatedAt
			}
			... on ServiceEntityOutline {
				__typename
				... on ApmAgentInstrumentedServiceEntityOutline {
					__typename
					applicationId
					language
				}
				... on GenericServiceEntityOutline {
					__typename
				}
			}
			... on SyntheticMonitorEntityOutline {
				__typename
				monitorId
				monitorType
				monitoredUrl
				period
			}
			... on ThirdPartyServiceEntityOutline {
				__typename
				... on GenericServiceEntityOutline {
					__typename
				}
			}
			... on UnavailableEntityOutline {
				__typename
			}
			... on WorkloadEntityOutline {
				__typename
				createdAt
				updatedAt
			}
		}
		entityTypes {
			domain
			type
		}
		nextCursor
	}
	types {
		count
		domain
		entityType
		type
	}
} } }`
