// Code generated by typegen; DO NOT EDIT.

package nerdstorage

// nolint:golint
type NerdStorageAccountScope struct {
	Collection []NerdStorageCollectionMember `json:"collection"`

	Document NerdStorageDocument `json:"document"`
}

// nolint:golint
type NerdStorageCollectionMember struct {
	Document NerdStorageDocument `json:"document"`

	ID string `json:"id,string"`
}

// nolint:golint
type NerdStorageDocument string

// nolint:golint
type NerdStorageScope string

const (
	ACCOUNT NerdStorageScope = "ACCOUNT" // nolint:golint
	ACTOR   NerdStorageScope = "ACTOR"   // nolint:golint
	ENTITY  NerdStorageScope = "ENTITY"  // nolint:golint
)

// nolint:golint
type NerdStorageScopeInput struct {
	ID string `json:"id,string"`

	Name NerdStorageScope `json:"name"`
}
